version: 2.1
orbs:
  orb-tools: circleci/orb-tools@8.27.4
  hub: 'mattvanstone/github@dev:alpha'
aliases:
  - &orb_name
    orb-name: mattvanstone/github
  - &ssh_fingerprint
    ssh-fingerprints: 87:b9:81:b8:6c:86:6c:46:0c:65:20:72:53:09:e5:55
jobs:
  integration-tests:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - hub/install
      - run: hub --version
workflows:
  integration-tests_prod-release:
    jobs:
      - integration-tests:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /integration-.*/
          name: integration-tests-dev
      - integration-tests:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-.*/
          name: integration-tests-master
      - orb-tools/dev-promote-prod:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-patch.*/
          name: dev-promote-patch
          <<: *orb_name
          requires:
            - integration-tests-master
      - orb-tools/dev-promote-prod:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-minor.*/
          name: dev-promote-minor
          <<: *orb_name
          release: minor
          requires:
            - integration-tests-master
      - orb-tools/dev-promote-prod:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-major.*/
          name: dev-promote-major
          <<: *orb_name
          release: major
          requires:
            - integration-tests-master
  lint_pack-validate_publish-dev:
    jobs:
      - orb-tools/lint
      - orb-tools/pack:
          requires:
            - orb-tools/lint
      - orb-tools/publish-dev:
          <<: *orb_name
          requires:
            - orb-tools/pack
      - orb-tools/trigger-integration-workflow:
          filters:
            branches:
              ignore: master
          name: trigger-integration-dev
          requires:
            - orb-tools/publish-dev
          <<: *ssh_fingerprint
      - orb-tools/trigger-integration-workflow:
          filters:
            branches:
              only: master
          name: trigger-integration-master
          requires:
            - orb-tools/publish-dev
          <<: *ssh_fingerprint
          tag: master
